version: '3.8'
services:
  api:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=your_db_user
      - DATABASE_PASSWORD=your_db_password
      - DATABASE_NAME=your_db_name
#   db:
#     image: postgres:13-alpine
#     restart: always
#     environment:
#       POSTGRES_USER: your_db_user
#       POSTGRES_PASSWORD: your_db_password
#       POSTGRES_DB: your_db_name
#     ports:
#       - '5432:5432'
#     volumes:
#       - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:
