name: FinalPOS CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      # Define a service for MongoDB
      mongo:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and run containers
        run: |
          docker-compose up -d --build
          # Wait until the API is ready
          sleep 15

      - name: Run integration tests
        run: |
          # Here you can run your test command, e.g., npm run test:e2e
          npm run test:e2e

      - name: Tear down containers
        run: |
          docker-compose down
