name: FPOS - CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run containers
        run: |
          docker-compose up -d --build

      - name: Wait for API to be ready
        run: |
          ./wait-for-it.sh localhost:3000 -t 30

      - name: Run integration tests
        run: npm run test:e2e

      - name: Tear down containers
        run: docker-compose down
